async function mpBuscarResp(input,area){const q=input.value.trim();if(q.length<2)return;
const{data:all}=await sb.from('mmbb_registrations').select('run,nombres,apellidos,foto_url').or(`run.ilike.%${q}%,nombres.ilike.%${q}%,apellidos.ilike.%${q}%`).limit(5);
const{data:adu}=await sb.from('adultos_registros').select('run,nombres,apellidos,foto_url').or(`run.ilike.%${q}%,nombres.ilike.%${q}%,apellidos.ilike.%${q}%`).limit(5);
let results=[...(all||[]).map(p=>({run:p.run,nombre:`${p.nombres} ${p.apellidos}`,foto:p.foto_url,tipo:'joven'})),...(adu||[]).map(a=>({run:a.run,nombre:`${a.nombres} ${a.apellidos}`,foto:a.foto_url,tipo:'adulto'}))];
const key=areaKey(area);const cont=input.parentElement.querySelector('.resp-result-'+key);
if(!results.length){cont.innerHTML='';return}
cont.innerHTML=`<div class="bg-white border border-gray-200 rounded-lg shadow-lg max-h-40 overflow-y-auto" style="width:100%;">${results.map(r=>`<div class="flex items-center gap-2 p-2 hover:bg-indigo-50 cursor-pointer text-sm" onclick="mpSelResp('${area}','${esc(r.run)}','${esc(r.nombre)}','${esc(r.foto||'')}','${r.tipo}');this.closest('.resp-result-${key}').innerHTML=''"><img src="${esc(r.foto||'')}" style="width:22px;height:22px;border-radius:50%;object-fit:cover;" onerror="this.style.display='none'"><span class="font-medium">${esc(r.nombre)}</span><span class="text-xs text-gray-400 ml-auto">${r.tipo}</span></div>`).join('')}</div>`}
function mpSelResp(area,run,nombre,foto,tipo){mpResponsables[area]={run,nombre,foto,tipo};renderMpResponsables();const key=areaKey(area);const cont=document.querySelector('.resp-result-'+key);if(cont)cont.innerHTML=''}
function renderMpResponsables(){AREAS_RESP.forEach(area=>{const key=areaKey(area);const el=document.getElementById('mp-resp-sel-'+key);if(!el)return;const r=mpResponsables[area];if(!r){el.innerHTML='';return}
el.innerHTML=`<div class="flex items-center gap-2 bg-indigo-50 border border-indigo-200 rounded-lg p-2"><img src="${esc(r.foto||'')}" style="width:24px;height:24px;border-radius:50%;object-fit:cover;" onerror="this.style.display='none'"><span class="text-xs font-bold">${esc(r.nombre)}</span><span class="text-xs text-indigo-500 font-bold ml-auto">${r.tipo}</span><button onclick="delete mpResponsables['${area}'];renderMpResponsables()" class="text-red-400 hover:text-red-600 ml-1"><i class="fas fa-times text-xs"></i></button></div>`})}

// Participantes search
async function mpBuscarParticipante(){const q=document.getElementById('mp-buscar-part').value.trim();if(q.length<2)return;
const{data:j}=await sb.from('mmbb_registrations').select('run,nombres,apellidos,foto_url').or(`run.ilike.%${q}%,apellidos.ilike.%${q}%,nombres.ilike.%${q}%`).limit(8);
const{data:a}=await sb.from('adultos_registros').select('run,nombres,apellidos,foto_url').or(`run.ilike.%${q}%,apellidos.ilike.%${q}%,nombres.ilike.%${q}%`).limit(5);
let all=[...(j||[]).map(p=>({run:p.run,nombre:`${p.nombres} ${p.apellidos}`,foto:p.foto_url,tipo:'joven'})),...(a||[]).map(p=>({run:p.run,nombre:`${p.nombres} ${p.apellidos}`,foto:p.foto_url,tipo:'adulto'}))];
const c=document.getElementById('mp-resultados-part');
if(!all.length){c.innerHTML='<p class="p-3 text-center text-gray-400 text-sm">Sin resultados.</p>';c.classList.remove('hidden');return}
c.innerHTML=all.map(r=>`<div class="flex items-center gap-2 p-2 cursor-pointer" onclick="mpAddParticipante('${esc(r.run)}','${esc(r.nombre)}','${esc(r.foto||'')}','${r.tipo}')"><img src="${esc(r.foto||'')}" style="width:24px;height:24px;border-radius:50%;object-fit:cover;" onerror="this.style.display='none'"><span class="text-sm font-medium">${esc(r.nombre)}</span><span class="text-xs text-gray-400 ml-auto">${r.tipo}</span></div>`).join('');c.classList.remove('hidden')}
function mpAddParticipante(run,nombre,foto,tipo){if(mpParticipantes.find(p=>p.run===run)){toast('Ya está agregado.','info');return}mpParticipantes.push({run,nombre,foto,tipo});renderMpParticipantes();document.getElementById('mp-resultados-part').classList.add('hidden');document.getElementById('mp-buscar-part').value=''}
function renderMpParticipantes(){document.getElementById('mp-participantes-list').innerHTML=mpParticipantes.map((p,i)=>`<div class="flex items-center gap-2 bg-gray-50 border border-gray-200 rounded-lg p-2"><img src="${esc(p.foto||'')}" style="width:28px;height:28px;border-radius:50%;object-fit:cover;" onerror="this.style.display='none'"><div><p class="text-xs font-bold">${esc(p.nombre)}</p><p class="text-xs text-gray-400">${p.tipo}</p></div><button onclick="mpParticipantes.splice(${i},1);renderMpParticipantes()" class="ml-auto text-red-400 hover:text-red-600"><i class="fas fa-times text-xs"></i></button></div>`).join('')}

// Evidencias
